name: Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Install Build Dependencies
        run: |
          sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg8 -y
          sudo apt-get update
          sudo apt-get install -y gcc pkg-config libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libswresample-dev libswscale-dev libavutil-dev

      - name: Build Binary
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -ldflags="-s -w" -o kokoro .

      - name: Prepare VPS for Upload
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            mkdir -p ~/kokoro
            [ -f ~/kokoro/kokoro ] && mv ~/kokoro/kokoro ~/kokoro/kokoro.old || true

      - name: Upload Binary to VPS
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "kokoro"
          target: "~/kokoro/"
          overwrite: true

      - name: Restart Bot on VPS
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/kokoro
            chmod +x kokoro
            nohup ./kokoro >> kokoro.log 2>&1 &
            sleep 1
